version: '3.0'
services:
  kafka:
    image: debezium/kafka:latest 
    container_name: kafka 
    hostname: kafka 
    networks:
     - debnet
    ports:
     - "9092:9092"
    links:
     - zookeeper:zookeeper
networks:
  debnet:
    driver: bridge
    driver_opts:
        com.docker.network.driver.mtu: 1500 
    ipam:
      config:
      - subnet: 172.30.0.0/16
