version: '3.0'
services:
  zookeeper:
    image: debezium/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    networks:
     - debnet
    ports:
     - "2181:2181"
     - "2888:2888"
     - "3888:3888"
networks:
  debnet:
    driver: bridge
    driver_opts:
        com.docker.network.driver.mtu: 1500 
    ipam:
      config:
      - subnet: 172.30.0.0/16
